[package]
name = "simple-icons-website-url"
description = "URL of the Simple Icons website"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web-sys.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
