[package]
name = "simple-icons-website"
description = "Simple Icons website main entrypoint"
version.workspace = true
edition.workspace = true

[dependencies]
simple-icons-website-components = { path = "../components" }
simple-icons-website-macros = { path = "../macros" }
simple-icons-website-i18n = { path = "../i18n" }
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
console_log.workspace = true
log.workspace = true
console_error_panic_hook.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["MediaQueryList"] }
serde_json.workspace = true
